name: "Terraform Plan and Apply"

on:
  push:
    paths:
      - "**.tf"
      - ".github/workflows/*"
  pull_request:
    branches:
      - main
    paths:
      - "**.tf"
      - ".github/workflows/*"

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  plan-and-apply:
    name: "tf workflow"
    uses: ./.github/workflows/tf-plan-apply.yaml
    strategy:
      matrix:
        target: [prod, nonprod]
    with:
      target: ${{ matrix.target }}
      tf-version: 1.9.1
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID}}
