name: "Terraform Infrastructure Change Management Pipeline with GitHub Actions"

on: 
  push: 
    branches:
    - main
    paths:
    - '**.tf'
    - '.github/workflows/*'
  pull_request:
    branches:
    - main
    paths:
    - '**.tf'
    - '.github/workflows/*'

env:
  TF_LOG: INFO
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID}}


jobs:
  terraform_plan:
    name: "Terraform Infrastructure Change Management"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.3
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform format
        id: fmt
        run: terraform fmt -check    
      - name: Terraform validate
        id: validate
        run: terraform validate
      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -input=false -out plan.tf
        continue-on-error: true
      - name: Archive Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: plan.tf

  apply:
    name: Terraform Apply
    needs: [terraform_plan]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download Plan File
        uses: actions/download-artifact@v4
        with:
          name: tfplan
      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.3
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false plan.tf